units = {
    "Worker": {
        "attack": 4,
        "recharge": 0,
        "hitpoints": 20,
        "range": 8,
        "sight": 6,
        "speed": 8,
        "cost": (0, 0, 50, 0),
        "time": 4,
    },
    "Scout": {
        "attack": 6,
        "recharge": 0,
        "hitpoints": 25,
        "range": 8,
        "sight": 10,
        "speed": 16,
        "cost": (0, 0, 50, 0),
        "time": 5,
    },
    "Swordsman": {
        "attack": 8,
        "recharge": 0,
        "hitpoints": 40,
        "range": 8,
        "sight": 8,
        "speed": 16,
        "cost": (10, 0, 100, 30),
        "time": 6,
    },
    "Archer": {
        "attack": 6,
        "recharge": 1,
        "hitpoints": 25,
        "range": 16 * 6,
        "sight": 8,
        "speed": 16,
        "cost": (10, 0, 180, 0),
        "time": 6,
    },
    "Lancer": {
        "attack": 10,
        "recharge": 0,
        "hitpoints": 40,
        "range": 16,
        "sight": 8,
        "speed": 12,
        "cost": (10, 0, 200, 30),
        "time": 8,
    },
    "Knight": {
        "attack": 12,
        "recharge": 0,
        "hitpoints": 50,
        "range": 16,
        "sight": 8,
        "speed": 28,
        "cost": (10, 0, 250, 10),
        "time": 10,
    },
    "Berserker": {
        "attack": 40,
        "recharge": 3,
        "hitpoints": 40,
        "range": 8,
        "sight": 8,
        "speed": 12,
        "cost": (10, 0, 220, 40),
        "time": 10,
    },
    "Mage": {
        "attack": 15,
        "recharge": 5,
        "hitpoints": 20,
        "range": 16 * 6,
        "sight": 8,
        "speed": 12,
        "cost": (10, 0, 320, 10),
        "time": 10,
    },
    "Assassin": {
        "attack": 25,
        "recharge": 0,
        "hitpoints": 25,
        "range": 8,
        "sight": 8,
        "speed": 24,
        "cost": (10, 0, 350, 10),
        "time": 10,
    },
    "Ballista": {
        "attack": 40,
        "recharge": 8,
        "hitpoints": 20,
        "range": 16 * 8,
        "sight": 4,
        "speed": 8,
        "cost": (200, 0, 350, 100),
        "time": 12,
    },
    "Mammoth": {
        "attack": 20,
        "recharge": 5,
        "hitpoints": 120,
        "range": 8,
        "sight": 4,
        "speed": 8,
        "cost": (0, 0, 450, 0),
        "time": 10,
    },
    "Battleship": {
        "attack": 30,
        "recharge": 5,
        "hitpoints": 140,
        "range": 5 * 16,
        "sight": 8,
        "speed": 24,
        "cost": (400, 0, 450, 200),
        "time": 10,
    },
    "Boat": {
        "attack": 0,
        "recharge": 0,
        "hitpoints": 50,
        "range": 0,
        "sight": 0,
        "speed": 16,
        "cost": (40, 0, 0, 0),
        "time": 1,
    },
}
